// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Coordinates struct {
	Latitude  float64 `json:"Latitude"`
	Longitude float64 `json:"Longitude"`
}

type Image struct {
	Filename string `json:"Filename"`
	Data     string `json:"Data"`
}

type LastSeenInfo struct {
	Timestamp   time.Time    `json:"Timestamp"`
	Coordinates *Coordinates `json:"Coordinates"`
}

type PageInfo struct {
	HasNextPage     bool   `json:"HasNextPage"`
	HasPreviousPage bool   `json:"HasPreviousPage"`
	StartCursor     string `json:"StartCursor"`
	EndCursor       string `json:"EndCursor"`
}

type Tiger struct {
	ID          string        `json:"ID"`
	Name        string        `json:"Name"`
	DateOfBirth time.Time     `json:"DateOfBirth"`
	LastSeen    *LastSeenInfo `json:"LastSeen"`
	LatestImage *Image        `json:"LatestImage"`
}

type TigerPagination struct {
	TotalCount int       `json:"TotalCount"`
	PageInfo   *PageInfo `json:"PageInfo"`
	Tigers     []*Tiger  `json:"Tigers"`
}

type User struct {
	Email string `json:"Email"`
}
